# -*- coding: utf-8 -*-
"""wine_knn_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AsWq80YcxHL4SDCDsN5HxkqaYZqZ9_eq
"""

from sklearn import datasets
import pandas as pd

# 데이터 불러오기
wine = datasets.load_wine()

df = pd.DataFrame(wine.data, columns=wine.feature_names)
df["class"] = wine.target
df

from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt

# 특성별 중요도 계산
X = df.drop("class", axis=1)
y = df["class"]

model = RandomForestClassifier(random_state=42)
model.fit(X, y)

importance = pd.Series(model.feature_importances_, index=X.columns)
print(importance)

importance.sort_values().plot(kind="barh", figsize=(8, 6))
plt.xlabel("Feature Importance")
plt.show()

# 두 주요 특성에 따른 클래스별 분포
plt.figure(figsize=(8, 6))

for c in sorted(df["class"].unique()):
    subset = df[df["class"] == c]
    plt.scatter(
        subset["flavanoids"],
        subset["color_intensity"],
        label=f"class {c}",
        alpha=0.7
    )

plt.xlabel("flavanoids")
plt.ylabel("color_intensity")
plt.title("Scatter Plot: flavanoids vs color_intensity by class")
plt.legend()
plt.show()

from sklearn.model_selection import train_test_split
import numpy as np

X = df.drop("class", axis=1)
y = df['class']

# 훈련 데이터, 테스트 데이터 분리
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=4)

from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

# k값에 따른 KNN 정확도
for k in range(1, 50, 6):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)

    y_pred = knn.predict(X_test)
    score = metrics.accuracy_score(y_test, y_pred)

    print(f"k={k}, accuracy={score:.4f}")