# -*- coding: utf-8 -*-
"""wine_knn_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AsWq80YcxHL4SDCDsN5HxkqaYZqZ9_eq
"""

from sklearn import datasets
import pandas as pd

# 데이터 불러오기
wine = datasets.load_wine()

df = pd.DataFrame(wine.data, columns=wine.feature_names)
df["class"] = wine.target
df

from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt

# 특성별 중요도 계산
X = df.drop("class", axis=1)
y = df["class"]

model = RandomForestClassifier(random_state=42)
model.fit(X, y)

importance = pd.Series(model.feature_importances_, index=X.columns)
print(importance)

importance.sort_values().plot(kind="barh", figsize=(8, 6))
plt.xlabel("Feature Importance")
plt.show()

# 두 주요 특성에 따른 클래스별 분포
plt.figure(figsize=(8, 6))

for c in sorted(df["class"].unique()):
    subset = df[df["class"] == c]
    plt.scatter(
        subset["flavanoids"],
        subset["color_intensity"],
        label=f"class {c}",
        alpha=0.7
    )

plt.xlabel("flavanoids")
plt.ylabel("color_intensity")
plt.title("Scatter Plot: flavanoids vs color_intensity by class")
plt.legend()
plt.show()

from sklearn.model_selection import train_test_split
import numpy as np

X = df.drop("class", axis=1)
y = df['class']

# 훈련 데이터, 테스트 데이터 분리
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=4)

# 데이터 정규화
X_train_mean = np.mean(X_train, axis=0)
X_train_std = np.std(X_train, axis=0)

X_train_norm = (X_train - X_train_mean) / X_train_std
X_test_norm = (X_test - X_train_mean) / X_train_std

print(X_train_norm.shape)
print(X_test_norm.shape)

from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

# k값에 따른 KNN 정확도
for k in range(1, 50, 6):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_norm, y_train)

    y_pred = knn.predict(X_test_norm)
    score = metrics.accuracy_score(y_test, y_pred)

    print(f"k={k}, accuracy={score:.4f}")

# 중요도 상위 n개의 특징 사용 시 정확도 평균
sorted_features = importance.sort_values(ascending=False).index

for top_n in range(1, len(sorted_features) + 1):
    selected_features = sorted_features[:top_n]

    X = df[selected_features]
    y = df["class"]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=4
    )

    X_train_mean = np.mean(X_train, axis=0)
    X_train_std = np.std(X_train, axis=0)

    X_train_norm = (X_train - X_train_mean) / X_train_std
    X_test_norm = (X_test - X_train_mean) / X_train_std

    score_list = []

    for k in range(1, 50, 6):
        knn = KNeighborsClassifier(n_neighbors=k)
        knn.fit(X_train_norm, y_train)

        y_pred = knn.predict(X_test_norm)
        score = metrics.accuracy_score(y_test, y_pred)
        score_list.append(score)

    mean_score = np.mean(score_list)
    print(f"top_features={top_n}, mean_accuracy={mean_score:.4f}")

# 중요도 상위 9개의 특징 사용
selected_features = sorted_features[:9]

X_top9 = df[selected_features]
y = df["class"]

X_mean = np.mean(X_top9, axis=0)
X_std = np.std(X_top9, axis=0)

X_norm = (X_top9 - X_mean) / X_std

# k=7
knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(X_norm, y)

# 신규 데이터 클래스 예측
new_data = pd.DataFrame([{
    "alcohol": 12.28,
    "malic_acid": 1.93,
    "ash": 2.24,
    "alcalinity_of_ash": 20.24,
    "magnesium": 94.55,
    "total_phenols": 2.26,
    "flavanoids": 2.08,
    "nonflavanoid_phenols": 0.36,
    "proanthocyanins": 1.63,
    "color_intensity": 3.09,
    "hue": 1.06,
    "od280/od315_of_diluted_wines": 2.79,
    "proline": 519.51
}])


new_data_selected = new_data[selected_features]
new_data_norm = (new_data_selected - X_mean) / X_std

pred = knn.predict(new_data_norm)
print("predicted class:", pred[0])